/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ControladorPrincipal;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Camiseta;
import model.Tamanho;

/**
 *
 * @author Richard
 */
public class TelaCRUDCamiseta extends javax.swing.JFrame {

    private ControladorPrincipal ctr;
    private DefaultTableModel modelo;
    private Camiseta camisetaSelecionada;
    private int status; // 1 - inserir - 2 - editar

    public TelaCRUDCamiseta(ControladorPrincipal aThis) {

        initComponents();
        this.ctr = aThis;
        setarComboTamanho();
        modelo = new DefaultTableModel();
        preencherCabecarioTabela();
        preencherTabela();
        this.status = 1;
        this.camisetaSelecionada = null;

        setLocationRelativeTo(null);
    }

    private void setarComboTamanho() {

        comboBoxTamanho.setModel(new DefaultComboBoxModel<>(Tamanho.values()));

    }

    private void preencherCabecarioTabela() {
        modelo.addColumn("Codigo");
        modelo.addColumn("Nome");
        modelo.addColumn("Tamanho");
        modelo.addColumn("Preço Custo");
        modelo.addColumn("Preço Venda");
        modelo.addColumn("Quantidade");
        modelo.addColumn("QM");

        tabela.setModel(modelo);
    }

    private void preencherTabela() {

        modelo.setNumRows(0);
        List<Camiseta> lista = ctr.getCtrCamisetas().listarCamisetas();

        for (Camiseta c : lista) {
            modelo.addRow(new Object[]{c.getCodigo(), c.getNome(), c.getTamanho(), c.getPrecoCusto(), c.getPrecoVenda(), c.getQuantidade(), c.getQm()});
        }
        tabela.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelBotoes = new javax.swing.JPanel();
        botaoVoltar = new javax.swing.JButton();
        botaoExcluir = new javax.swing.JButton();
        botaoEditar = new javax.swing.JButton();
        botaoNovo = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        botaoSalvar = new javax.swing.JButton();
        textoNome = new javax.swing.JTextField();
        textoTag = new javax.swing.JTextField();
        textoPrecoCusto = new javax.swing.JTextField();
        textoPrecoVenda = new javax.swing.JTextField();
        textoQM = new javax.swing.JTextField();
        comboBoxTamanho = new javax.swing.JComboBox<>();
        botaoMais = new javax.swing.JButton();
        botaoMenos = new javax.swing.JButton();
        comboBoxQuantidade = new javax.swing.JComboBox<>();
        botaoLimpar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastro de Camiseta");

        botaoVoltar.setText("Voltar");
        botaoVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVoltarActionPerformed(evt);
            }
        });

        botaoExcluir.setText("Excluir");
        botaoExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoExcluirActionPerformed(evt);
            }
        });

        botaoEditar.setText("Editar");
        botaoEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoEditarActionPerformed(evt);
            }
        });

        botaoNovo.setText("Novo");
        botaoNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoNovoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelBotoesLayout = new javax.swing.GroupLayout(painelBotoes);
        painelBotoes.setLayout(painelBotoesLayout);
        painelBotoesLayout.setHorizontalGroup(
            painelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelBotoesLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(botaoVoltar)
                .addGap(59, 59, 59)
                .addComponent(botaoExcluir)
                .addGap(62, 62, 62)
                .addComponent(botaoEditar)
                .addGap(64, 64, 64)
                .addComponent(botaoNovo)
                .addContainerGap(45, Short.MAX_VALUE))
        );
        painelBotoesLayout.setVerticalGroup(
            painelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelBotoesLayout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addGroup(painelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoExcluir)
                    .addComponent(botaoEditar)
                    .addComponent(botaoNovo)
                    .addComponent(botaoVoltar))
                .addGap(22, 22, 22))
        );

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tabela);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );

        jLabel1.setText("Nome:*");

        jLabel2.setText("HashTag:");

        jLabel3.setText("Preço custo:*");

        jLabel4.setText("Preço venda:*");

        jLabel5.setText("QM:*");

        jLabel6.setText("Tamanho:");

        jLabel7.setText("Quantidade:");

        botaoSalvar.setText("Salvar");
        botaoSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSalvarActionPerformed(evt);
            }
        });

        textoNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoNomeActionPerformed(evt);
            }
        });

        comboBoxTamanho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxTamanhoActionPerformed(evt);
            }
        });

        botaoMais.setText("+");
        botaoMais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoMaisActionPerformed(evt);
            }
        });

        botaoMenos.setText("-");
        botaoMenos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoMenosActionPerformed(evt);
            }
        });

        comboBoxQuantidade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0" ,"1", "2", "3", "4", "5","6","7","8","9","10" }));
        comboBoxQuantidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxQuantidadeActionPerformed(evt);
            }
        });

        botaoLimpar.setText("Limpar");
        botaoLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoLimparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(comboBoxTamanho, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(comboBoxQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(botaoMais)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botaoMenos)
                        .addGap(36, 36, 36))
                    .addComponent(textoPrecoVenda)
                    .addComponent(textoQM)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(textoNome, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                                .addComponent(textoTag)
                                .addComponent(textoPrecoCusto))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(botaoLimpar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(botaoSalvar)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(textoNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(textoTag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(textoPrecoCusto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(textoPrecoVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(textoQM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(comboBoxTamanho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(botaoMais)
                    .addComponent(botaoMenos)
                    .addComponent(comboBoxQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoSalvar)
                    .addComponent(botaoLimpar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(painelBotoes, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(4, 4, 4))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(7, 7, 7)
                .addComponent(painelBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textoNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoNomeActionPerformed

    private void botaoMaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoMaisActionPerformed
        if (comboBoxQuantidade.getSelectedIndex() < 10) {
            comboBoxQuantidade.setSelectedIndex(comboBoxQuantidade.getSelectedIndex() + 1);
        }
    }//GEN-LAST:event_botaoMaisActionPerformed

    private void botaoVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoVoltarActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_botaoVoltarActionPerformed

    private void comboBoxTamanhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxTamanhoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxTamanhoActionPerformed

    private boolean validadorCamposObrigatorios() {
        boolean retorno = false;
        if (!textoNome.getText().trim().equals("") && !textoPrecoCusto.getText().trim().equals("")
                && !textoPrecoVenda.getText().trim().equals("") && !textoQM.getText().trim().equals("")) {
            retorno = true;
        }
        return retorno;
    }

    private void botaoSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSalvarActionPerformed
        if (validadorCamposObrigatorios()) {
            if (comboBoxQuantidade.getSelectedIndex() >= Integer.parseInt(textoQM.getText())) {
                if (status == 1) {

                    Camiseta camiseta = new Camiseta(textoNome.getText().trim(), textoTag.getText().trim(), Double.parseDouble(textoPrecoCusto.getText().trim()),
                            Double.parseDouble(textoPrecoVenda.getText().trim()), Integer.parseInt(textoQM.getText().trim()),
                            comboBoxQuantidade.getSelectedIndex(), (Tamanho) comboBoxTamanho.getSelectedItem());
                    ctr.getCtrCamisetas().inserir(camiseta);

                } else if (status == 2) {
                    camisetaSelecionada.setNome(textoNome.getText().trim());
                    camisetaSelecionada.setHashTag(textoTag.getText().trim());
                    camisetaSelecionada.setPrecoCusto(Double.parseDouble(textoPrecoCusto.getText().trim()));
                    camisetaSelecionada.setPrecoVenda(Double.parseDouble(textoPrecoVenda.getText().trim()));
                    camisetaSelecionada.setQm(Integer.parseInt(textoQM.getText().trim()));
                    camisetaSelecionada.setQuantidade(comboBoxQuantidade.getSelectedIndex());
                    camisetaSelecionada.setTamanho((Tamanho) comboBoxTamanho.getSelectedItem());
                    ctr.getCtrCamisetas().atualizar(camisetaSelecionada);
                    limparCampos();
                }
                preencherTabela();
            } else {
                JOptionPane.showMessageDialog(null, "Quantidade em estoque deve ser maior que QM");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Preencher todos os campos obrigatorios!");
        }
    }//GEN-LAST:event_botaoSalvarActionPerformed

    private void limparCampos() {
        textoNome.setText("");
        textoTag.setText("");
        textoPrecoCusto.setText("");
        textoPrecoVenda.setText("");
        textoQM.setText("");
        comboBoxTamanho.setSelectedIndex(0);
        comboBoxQuantidade.setSelectedIndex(0);
    }

    private void setStatus(int i) {
        this.status = i;
    }


    private void botaoLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoLimparActionPerformed
        limparCampos();
    }//GEN-LAST:event_botaoLimparActionPerformed

    private void botaoMenosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoMenosActionPerformed

        if (comboBoxQuantidade.getSelectedIndex() > 0) {
            comboBoxQuantidade.setSelectedIndex(comboBoxQuantidade.getSelectedIndex() - 1);
        }
    }//GEN-LAST:event_botaoMenosActionPerformed

    private void botaoNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoNovoActionPerformed
        setStatus(1);
        limparCampos();
    }//GEN-LAST:event_botaoNovoActionPerformed

    private void botaoEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoEditarActionPerformed

        setStatus(2);
        int selecionado = tabela.getSelectedRow();
        if (selecionado >= 0) {
            camisetaSelecionada = ctr.getCtrCamisetas().pesquisarPorCodigo((int) tabela.getValueAt(selecionado, 0));
            if (camisetaSelecionada != null) {
                textoNome.setText(camisetaSelecionada.getNome().trim());
                textoTag.setText(camisetaSelecionada.getHashTag().trim());
                textoPrecoCusto.setText(Double.toString(camisetaSelecionada.getPrecoCusto()));
                textoPrecoVenda.setText(Double.toString(camisetaSelecionada.getPrecoVenda()));
                textoQM.setText(Integer.toString(camisetaSelecionada.getQm()));
                comboBoxQuantidade.setSelectedIndex(camisetaSelecionada.getQuantidade());
                comboBoxTamanho.setSelectedItem(camisetaSelecionada.getTamanho());
            } else {
                JOptionPane.showMessageDialog(null, "Camiseta não selecionada");
            }
        }
    }//GEN-LAST:event_botaoEditarActionPerformed

    private void botaoExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoExcluirActionPerformed
        int selecionado = tabela.getSelectedRow();
        if (selecionado >= 0) {
            ctr.getCtrCamisetas().excluir((int) tabela.getValueAt(selecionado, 0));
            preencherTabela();

        } else {
            JOptionPane.showMessageDialog(null, "Camiseta não selecionada");
        }
    }//GEN-LAST:event_botaoExcluirActionPerformed

    private void comboBoxQuantidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxQuantidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxQuantidadeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoEditar;
    private javax.swing.JButton botaoExcluir;
    private javax.swing.JButton botaoLimpar;
    private javax.swing.JButton botaoMais;
    private javax.swing.JButton botaoMenos;
    private javax.swing.JButton botaoNovo;
    private javax.swing.JButton botaoSalvar;
    private javax.swing.JButton botaoVoltar;
    private javax.swing.JComboBox<String> comboBoxQuantidade;
    private javax.swing.JComboBox<Tamanho> comboBoxTamanho;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel painelBotoes;
    private javax.swing.JTable tabela;
    private javax.swing.JTextField textoNome;
    private javax.swing.JTextField textoPrecoCusto;
    private javax.swing.JTextField textoPrecoVenda;
    private javax.swing.JTextField textoQM;
    private javax.swing.JTextField textoTag;
    // End of variables declaration//GEN-END:variables
}
